window.DiscTests = (function () {
    var DISC_QUESTIONS = [
        { q:'Face à une décision urgente, vous…', opts:[ {t:'D',l:'Décidez immédiatement sans attendre les autres'}, {t:'I',l:'Consultez l\'équipe pour créer de l\'adhésion'}, {t:'S',l:'Prenez le temps d\'évaluer l\'impact sur tout le monde'}, {t:'C',l:'Rassemblez d\'abord toutes les informations disponibles'} ] },
        { q:'Dans une réunion conflictuelle, vous avez tendance à…', opts:[ {t:'D',l:'Prendre le lead et trancher rapidement'}, {t:'I',l:'Alléger la tension avec humour et enthousiasme'}, {t:'S',l:'Écouter patiemment et chercher le consensus'}, {t:'C',l:'Analyser les faits pour trouver la solution objective'} ] },
        { q:'Ce qui vous motive le plus au travail est…', opts:[ {t:'D',l:'Atteindre des résultats concrets et gagner'}, {t:'I',l:'Travailler avec des gens enthousiastes et créatifs'}, {t:'S',l:'La stabilité et l\'harmonie de l\'équipe'}, {t:'C',l:'Faire un travail de qualité irréprochable'} ] },
        { q:'Votre style de communication naturel est…', opts:[ {t:'D',l:'Direct et concis — vous allez droit au but'}, {t:'I',l:'Chaleureux et expressif — vous animez la conversation'}, {t:'S',l:'Posé et attentif — vous laissez parler les autres'}, {t:'C',l:'Précis et détaillé — vous documentez vos propos'} ] },
        { q:'Sous pression, vous devenez plutôt…', opts:[ {t:'D',l:'Autoritaire et impulsif'}, {t:'I',l:'Bavard et distrait'}, {t:'S',l:'Passif et résistant au changement'}, {t:'C',l:'Perfectionniste et paralysé par les détails'} ] },
        { q:'Pour un projet, vous commencez par…', opts:[ {t:'D',l:'Définir l\'objectif et déléguer'}, {t:'I',l:'Partager l\'idée et mobiliser l\'équipe'}, {t:'S',l:'Planifier les étapes en consultant chacun'}, {t:'C',l:'Analyser les risques et établir un protocole'} ] },
        { q:'En cas d\'erreur dans l\'équipe, vous…', opts:[ {t:'D',l:'Identifiez le responsable et corrigez vite'}, {t:'I',l:'Transformez ça en opportunité d\'apprentissage positif'}, {t:'S',l:'Soutenez la personne et cherchez une solution douce'}, {t:'C',l:'Analysez la cause racine pour éviter la récidive'} ] },
        { q:'Ce que les autres apprécient chez vous…', opts:[ {t:'D',l:'Votre efficacité et votre leadership'}, {t:'I',l:'Votre énergie et votre positivité contagieuse'}, {t:'S',l:'Votre fiabilité et votre empathie'}, {t:'C',l:'Votre rigueur et votre expertise'} ] },
        { q:'Votre rapport au temps est…', opts:[ {t:'D',l:'Urgent — tout devrait aller plus vite'}, {t:'I',l:'Flexible — le timing s\'adapte aux opportunités'}, {t:'S',l:'Stable — les changements de planning vous perturbent'}, {t:'C',l:'Planifié — vous respectez scrupuleusement les délais'} ] },
        { q:'Dans une formation, vous apprenez mieux quand…', opts:[ {t:'D',l:'C\'est orienté résultats concrets et applicable immédiatement'}, {t:'I',l:'C\'est interactif, stimulant, avec des échanges riches'}, {t:'S',l:'C\'est structuré, progressif, avec un accompagnement bienveillant'}, {t:'C',l:'C\'est documenté, rigoureux, avec des données précises'} ] },
        { q:'Face à un changement organisationnel, vous…', opts:[ {t:'D',l:'L\'impulsez ou y résistez frontalement'}, {t:'I',l:'L\'accueillez avec enthousiasme et convainquez les sceptiques'}, {t:'S',l:'L\'acceptez progressivement si l\'équipe est impliquée'}, {t:'C',l:'L\'analysez en profondeur avant de vous positionner'} ] },
        { q:'Votre plus grand point d\'attention en communication est…', opts:[ {t:'D',l:'Ne pas couper la parole des autres trop souvent'}, {t:'I',l:'Aller jusqu\'au bout des idées sans se disperser'}, {t:'S',l:'Oser exprimer votre désaccord'}, {t:'C',l:'Ne pas noyer l\'interlocuteur dans les détails'} ] }
    ];
    var VAKOG_QUESTIONS = [
        { q:'Pour apprendre un nouveau geste technique, vous préférez…', opts:[ {t:'V',l:'Observer une démonstration, voir un schéma'}, {t:'A',l:'Écouter les explications orales étape par étape'}, {t:'K',l:'Pratiquer directement, sentir le geste dans vos mains'}, {t:'O',l:'Être immergé dans l\'ambiance du bloc'}, {t:'G',l:'Obtenir un retour concret sur votre ressenti global'} ] },
        { q:'Quand vous mémorisez une information, vous la…', opts:[ {t:'V',l:'Visualisez mentalement, sous forme de schéma ou image'}, {t:'A',l:'Répétez oralement ou entendez dans votre tête'}, {t:'K',l:'Associez à une sensation physique ou un geste'}, {t:'O',l:'Associez à une odeur ou une ambiance particulière'}, {t:'G',l:'Associez à une émotion ou satisfaction ressentie'} ] },
        { q:'En salle de réveil, ce qui attire d\'abord votre attention, c\'est…', opts:[ {t:'V',l:'L\'état visuel du patient, les écrans, les dispositifs'}, {t:'A',l:'Les sons — respiration, alarmes, voix du patient'}, {t:'K',l:'Le toucher — température, pouls, tonicité cutanée'}, {t:'O',l:'L\'odeur de la salle, du patient, des produits'}, {t:'G',l:'La sensation générale de l\'atmosphère de la salle'} ] },
        { q:'Pour expliquer une procédure à un étudiant, vous…', opts:[ {t:'V',l:'Montrez un schéma ou écrivez les étapes'}, {t:'A',l:'Expliquez oralement avec un rythme et une intonation clairs'}, {t:'K',l:'Faites-lui mimer ou expérimenter le geste'}, {t:'O',l:'Créez une ambiance propice à la concentration'}, {t:'G',l:'Utilisez des métaphores de ressenti pour illustrer'} ] },
        { q:'Quand vous êtes concentré, vous avez besoin…', opts:[ {t:'V',l:'D\'un espace visuellement organisé et dégagé'}, {t:'A',l:'De silence ou d\'une musique de fond régulière'}, {t:'K',l:'D\'être en mouvement ou de manipuler quelque chose'}, {t:'O',l:'D\'une odeur apaisante ou d\'un environnement olfactivement neutre'}, {t:'G',l:'D\'un environnement qui "goûte bien" — confortable, doux'} ] },
        { q:'En transmissions orales, vous retenez mieux…', opts:[ {t:'V',l:'Quand c\'est illustré de chiffres, tableaux, schémas'}, {t:'A',l:'Quand le débit est rythmé et la voix modulée'}, {t:'K',l:'Quand vous pouvez poser des questions et interagir'}, {t:'O',l:'Quand l\'atmosphère est détendue et la relation fluide'}, {t:'G',l:'Quand vous ressentez la satisfaction d\'une information bien intégrée'} ] },
        { q:'Une séance de simulation qui vous marque, c\'est une séance où…', opts:[ {t:'V',l:'Vous avez vu des gestes nets, un scenario clair et structuré'}, {t:'A',l:'Les débriefings étaient vivants, les échanges riches'}, {t:'K',l:'Vous avez mis les mains dedans, pratiqué pour de vrai'}, {t:'O',l:'L\'ambiance était réaliste, presque comme au bloc'}, {t:'G',l:'Vous avez ressenti la satisfaction de progresser'} ] },
        { q:'Quand vous êtes stressé en situation, vous…', opts:[ {t:'V',l:'Cherchez des repères visuels — checklist, monitor, protocole affiché'}, {t:'A',l:'Verbalisez mentalement ou cherchez à entendre une voix calme'}, {t:'K',l:'Avez besoin de faire quelque chose de concret des mains'}, {t:'O',l:'Cherchez à retrouver une ambiance rassurante'}, {t:'G',l:'Cherchez une confirmation interne que les choses se passent bien'} ] },
        { q:'Ce qui vous dérange le plus dans une mauvaise communication, c\'est…', opts:[ {t:'V',l:'Le manque de clarté visuelle — rien d\'écrit, rien de montré'}, {t:'A',l:'Un ton inadapté, une voix monocorde ou trop agressive'}, {t:'K',l:'L\'absence de contact humain, de chaleur relationnelle'}, {t:'O',l:'Une ambiance lourde, des tensions dans l\'air'}, {t:'G',l:'L\'impression que la relation ne "goûte pas bien"'} ] },
        { q:'Pour vous, une formation réussie, c\'est avant tout…', opts:[ {t:'V',l:'Des supports visuels clairs, un plan affiché, des schémas'}, {t:'A',l:'Un formateur à l\'écoute, des échanges verbaux riches'}, {t:'K',l:'Des exercices pratiques, des mises en situation réelles'}, {t:'O',l:'Une atmosphère bienveillante et immersive'}, {t:'G',l:'Une progression ressentie, une satisfaction palpable'} ] }
    ];
    return Object.freeze({ DISC_QUESTIONS:DISC_QUESTIONS, VAKOG_QUESTIONS:VAKOG_QUESTIONS });
}());

